# Generated by Django 4.1.2 on 2022-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproducts',
            fields=[
                ('Productsid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=6)),
                ('image', models.ImageField(default='default.jpg', upload_to='proimg/')),
            ],
        ),
    ]
