# Generated by Django 4.1.2 on 2022-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
