# Generated by Django 4.1.2 on 2022-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_addproducts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='Productsid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
