# Generated by Django 4.1.2 on 2022-10-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Melcom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=120)),
                ('productCat', models.CharField(choices=[('Mobiles&Acc', 'Mobiles Phones & Accessories'), ('Computers&Acc', 'Computers & Accessories'), ('KitchenAppliance', 'Kitchen Appliances')], max_length=120)),
                ('productPrice', models.CharField(max_length=6)),
                ('productImage', models.ImageField(default='default.jpg', upload_to='melcom/')),
                ('productWebAddress', models.URLField()),
                ('dateadded', models.DateField(auto_now=True)),
            ],
        ),
    ]
