# Generated by Django 4.1.2 on 2022-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_melcom_productdespription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melcom',
            name='productWebAddress',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='melcom',
            name='productPrice',
            field=models.CharField(max_length=100),
        ),
    ]
