# Generated by Django 4.1.2 on 2022-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_melcom_productwebaddress_alter_melcom_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='melcom',
            name='store',
            field=models.CharField(blank=True, choices=[('Melcom', 'Melcom'), ('CampuGhana', 'CampuGhana'), ('Franko', 'Franko Trading'), ('LG', 'LG'), ('Hisense', 'Hisense'), ('Samsung', 'Samsung'), ('Techno', 'Techno Ghana'), ('Goodluck', 'GoodLuck Africa')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='melcom',
            name='productCat',
            field=models.CharField(choices=[('Mobiles&Acc', 'Mobiles Phones & Accessories'), ('Computers&Acc', 'Computers & Accessories'), ('KitchenAppliance', 'Kitchen Appliances')], max_length=120),
        ),
    ]
